inherit: true

# See https://github.com/scrutinizer-ci/scrutinizer/issues/399
checks:
  php: true

build:
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]

filter:
  paths: ["src/*", "tests/*"]
