language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_TEST=1
    - php: 7.2
      env: PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1

 #  PHP 7.4 and php-vcr seem to have some compatability issues, look at with fresh eyes tomorrow
 #   - php: 7.4
 #     env: PHPUNIT_TEST=1

    # Code compliance
    - php: 7.4
      env: PHPCS_TEST=1
    - php: 7.4
      env: PHPSTAN_TEST=1
    - php: 7.4
      env: PSALM_TEST=1

env:
  global:
    - PHPSTAN_VERSION=^0.12

services:
  -  docker

before_install:
  - docker pull manticoresearch/manticore
  - docker network create manticore
  - docker run --rm --publish 9308:9308 --network manticore --name=manticoresearch-manticore --detach manticoresearch/manticore

before_script:
  - composer validate
  #- if [[ $PHPSTAN_TEST ]]; then composer require --dev phpstan/phpstan && composer require php-http/discovery php-http/curl-client guzzlehttp/psr7 php-http/message http-interop/http-factory-guzzle; fi

install:
  # See https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
  - composer global require hirak/prestissimo
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G  tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   tests/   ; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 src/ tests/ ; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=3 -c tests/phpstan.neon src/; fi
  - if [[ PSALM_TEST ]]; then ./vendor/bin/psalm --show-info=true; fi

after_script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
