language: php

dist: xenial

matrix:
  include:
    - php: 7.1
      env: INSTALLER_VERSION=4.5 PHPUNIT_TEST=1
    - php: 7.2
      env: INSTALLER_VERSION=4.6 PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: INSTALLER_VERSION=4.4.x-dev PHPUNIT_TEST=1
    - php: 7.4
      env: INSTALLER_VERSION=4.4.x-dev PHPUNIT_TEST=1

    # Code compliance
    - php: 7.4
      env: INSTALLER_VERSION=4.4.x-dev PHPCS_TEST=1
    - php: 7.4
      env: INSTALLER_VERSION=4.4.x-dev PHPSTAN_TEST=1
    - php: 7.4
      env: INSTALLER_VERSION=4.4.x-dev PSALM_TEST=1



before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$INSTALLER_VERSION
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit tests --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi


after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
