language: php

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - UNIT_TESTING_CONFIG_ENABLED=1


matrix:
  include:
    # Code compliance
    - php: 7.4
      env: INSTALLER_VERSION=4.5 PHPCS_TEST=1
    - php: 7.4
      env: INSTALLER_VERSION=4.5 PHPSTAN_TEST=1

    # Code
    - php: 7.1
      env: INSTALLER_VERSION=4.4 PHPUNIT_TEST=1
    - php: 7.2
      env: INSTALLER_VERSION=4.4 PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: INSTALLER_VERSION=4.5 PHPUNIT_TEST=1
    - php: 7.4
      env: INSTALLER_VERSION=4.5.x-dev PHPUNIT_TEST=1


services:
  - docker
  - mysql

before_install:
  - docker pull manticoresearch/manticore
  - docker network create manticore
  - docker run --rm --publish 9308:9308 --network manticore --name=manticoresearch-manticore --detach manticoresearch/manticore
  - docker ps

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer validate
  - composer global require hirak/prestissimo

  - composer require --no-update silverstripe/recipe-cms:$INSTALLER_VERSION
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

  - vendor/bin/sake dev/build flush=all

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit tests --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 src/ tests/ ; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=3 -c tests/phpstan.neon src/; fi

after_script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
