language: php

dist: xenial

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
addons:
  - postgresql: 12
  - apt:
    - update: true
    - packages:

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev

matrix:
  include:
#    - php: 7.1
#      env: DB=PGSQL RECIPE_VERSION=4.3.x-dev  PHPUNIT_TEST=1
#    - php: 7.2
#      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_COVERAGE_TEST=1
#    - php: 7.3
#      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1
#    - php: 7.3
#      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1
#    - php: 7.3
#      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPCS_TEST=1

before_script:
  - sudo apt-get -y remove postgresql postgresql-client
  - sudo find /etc/apt
  - sudo apt-get update
  - sudo apt install postgresql postgresql-client wget
  #- sudo su -postgres /usr/lib/postgresql/12/bin/pg_ctl -D /var/lib/postgresql/12/main -l logfile start
  - sudo service postgresql start
  - psql -c 'create database travis_ci_test;' -U postgres
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - wget https://github.com/manticoresoftware/manticoresearch/releases/download/3.3.0/manticore_3.3.0-200204-01fc8ad-release.xenial_amd64-bin.deb
  - sudo apt install -y ./manticore_3.3.0-200204-01fc8ad-release.xenial_amd64-bin.deb
  - rm ./manticore_3.3.0-200204-01fc8ad-release.xenial_amd64-bin.deb



  # Install composer dependencies
  - composer validate # --strict here?
  - composer require silverstripe/recipe-cms:"$RECIPE_VERSION" --no-update
  - if [[ $BEHAT_TEST ]]; then composer require --no-update silverstripe/behat-extension:4.x-dev; fi;
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2 --no-update; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile


    # Run dev/build
  - vendor/bin/sake dev/build flush=all

    # Dump constants for debug
  - php vendor/silverstripe/framework/tests/dump_constants.php

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G  tests/ '' flush=1; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   tests/ '' flush=1  ; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --config-set ignore_errors_on_exit 1 && vendor/bin/phpcs --config-set ignore_warnings_on_exit 1 && vendor/bin/phpcs src/ tests/ ; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run test; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @silverstripe-elemental; fi
  -
after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
