language: php
dist: bionic
cache:
    directories:
        - $HOME/.composer/cache/files
matrix:
    include:
        -
            php: 7.4
            env: 'INSTALLER_VERSION=4.5 PHPCS_TEST=1'
        -
            php: 7.4
            env: 'INSTALLER_VERSION=4.5 PHPSTAN_TEST=1'
        -
            php: 7.1
            env: 'INSTALLER_VERSION=4.4 PHPUNIT_TEST=1'
        -
            php: 7.2
            env: 'INSTALLER_VERSION=4.4 PHPUNIT_COVERAGE_TEST=1'
        -
            php: 7.3
            env: 'INSTALLER_VERSION=4.5 PHPUNIT_TEST=1'
        -
            php: 7.4
            env: 'INSTALLER_VERSION=4.5.x-dev PHPUNIT_TEST=1'
        -
            php: 7.4
            env: PHPCS_TEST=1
        -
            php: 7.4
            env: DUPLICATE_CODE_CHECK=1
        -
            php: 7.4
            env: LINT_CHECK=1
        -
            php: 7.4
            env: PHPSTAN_TEST=1
services:
    - docker
    - mysql
before_install:
    - 'docker pull manticoresearch/manticore'
    - 'docker network create manticore'
    - 'docker run --rm --publish 9308:9308 --network manticore --name=manticoresearch-manticore --detach manticoresearch/manticore'
    - 'docker ps'
install:
    - 'composer validate'
    - 'composer global require hirak/prestissimo'
    - 'composer require --no-update silverstripe/recipe-cms:$INSTALLER_VERSION'
    - 'composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile'
    - 'export UNIT_TESTING_CONFIG_ENABLED=1'
before_script:
    - 'phpenv rehash'
    - 'phpenv config-rm xdebug.ini'
    - 'echo ''memory_limit = 2G'' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
    - 'if [[ $DUPLICATE_CODE_CHECK ]]; then sudo apt remove -y nodejs && curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh && sudo apt install -y build-essential nodejs && which npm && npm install jscpd@3.2.1  ;fi'
script:
    - 'if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests '''' flush=all; fi'
    - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit tests --coverage-clover=coverage.xml '''' flush=all; fi'
    - 'if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 src/ tests/ ; fi'
    - 'if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=3 -c tests/phpstan.neon src/; fi'
    - 'if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests ; fi'
    - 'if [[ $DUPLICATE_CODE_CHECK ]]; then node_modules/jscpd/bin/jscpd src && node_modules/jscpd/bin/jscpd tests ; fi'
    - 'if [[ $LINT_CHECK ]]; then vendor/bin/parallel-lint src/ tests/ ; fi'
    - 'if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=6 -c tests/phpstan.neon src/ ; fi'
after_script:
    - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi'
