<?php
namespace Suilven\ManticoreSearch\Tests;

use SilverStripe\Dev\SapphireTest;
use SilverStripe\ORM\DataObject;
use Suilven\FreeTextSearch\Indexes;
use Suilven\ManticoreSearch\Helper\IndexingHelper;
use Suilven\ManticoreSearch\Service\Indexer;
use Suilven\ManticoreSearch\Service\Searcher;
use Suilven\ManticoreSearch\Service\Suggester;
use Suilven\ManticoreSearch\Tests\Models\FlickrAuthor;
use Suilven\ManticoreSearch\Tests\Models\FlickrSet;
use Suilven\ManticoreSearch\Tests\Models\FlickrTag;

class SearchTest extends SapphireTest
{
    protected static $extra_dataobjects = [
        FlickrPhoto::class,
        FlickrTag::class,
        FlickrSet::class,
        FlickrAuthor::class
    ];

    /**
     * @var int
     */
    private static $pageID;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        $page = new \Page();
        $page->Title = 'Hometown Sandlot Knitted Saddens Days';
        $page->Content = 'Webmaster fakes disconnections overdose.  Windowing preschooler malfunctions dolts statutes.';
        $page->write();
        self::$pageID = $page->ID;
    }

    public function setUp()
    {
        parent::setUp();
        $indexesService = new Indexes();
        $indexesObj = $indexesService->getIndexes();
        $indexer = new Indexer($indexesObj);
        $indexer->reconfigureIndexes();
    }

    public function test_index_one_document_and_suggest()
    {
        $helper = new IndexingHelper();
        $doc = DataObject::get_by_id(\Page::class, self::$pageID);
        $helper->indexObject($doc);

        // search for webmister, a deliberate error (should be webmaster)
        $suggester = new Suggester();
        $suggester->setIndex('sitetree');
        $suggestions = $suggester->suggest('webmister');
        $this->assertEquals(['webmaster'], $suggestions);
    }


    public function test_index_one_document_and_search()
    {
        $helper = new IndexingHelper();
        $doc = DataObject::get_by_id(\Page::class, self::$pageID);
        $helper->indexObject($doc);

        $searcher = new Searcher();
        $searcher->setIndex('sitetree');
        $result = $searcher->search('Webmaster disconnections');
        $result = $result->toArray();

        error_log(print_r($result, 1));
    }
}
