# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: brettt89/silverstripe-web:7.1-platform
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    branches:
      only:
        - master
        - develop
        - travis

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: pwd
      - run: ls -lh
      - run: cat /etc/issue
      - run: apt-get update && apt-get install -y wget libmysqlclient18 libodbc1 libpq5 mysql-client
      - run: wget http://sphinxsearch.com/files/sphinxsearch_2.3.2-beta-1~jessie_amd64.deb && dpkg -i sphinxsearch_2.3.2-beta-1~jessie_amd64.deb && rm sphinxsearch_2.3.2-beta-1~jessie_amd64.deb
      #- run: service sphinxsearch start
      - run: cp /etc/sphinxsearch/sphinx.conf ~/sphinxdefault.conf
      - run: composer validate
      - run: composer require --prefer-dist --no-update silverstripe/recipe-cms:1.1.x-dev
      - run: composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run test,upload coverage
      - run: phpdbg -qrr vendor/bin/phpunit -d memory_limit=512M --coverage-clover=coverage.xml tests
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.xml

