name: PHP Composer

on:
  push:
    branches: [ master, CI2 ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php-version: [ 7.3, 7.4 ]
      fail-fast: false

    steps:
    - name: Set up .env file
      run: wget "https://raw.githubusercontent.com/silverstripe/github-actions-ci-cd/main/.github/things/.env"

    - name: Run tests
      run: |
        echo "PWD"
        pwd
        echo "Dir listing"
        ls -lh
        echo "Run tests"
        ./vendor/bin/phpunit tests



  # Install PHP, checkout code, validate composer
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.3, 7.4]

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-version }} with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl, dom, gd, intl, json, ldap, mbstring, mysql, tidy, zip

    - name: Check OS
      id: checkos
      run: |
        cat /etc/issue
        php --version

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check installed
      run: |
        composer info | grep phpunit
        ls -lh vendor/bin
        find . | grep phpunit

